import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  javascriptSidebar: [{ type: 'autogenerated', dirName: 'javascript' }],
  wordpressSidebar: [{ type: 'autogenerated', dirName: 'wordpress' }],
};

export default sidebars;