import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  javascriptSidebar: [{ type: 'autogenerated', dirName: 'javascript' }],
};

export default sidebars;