import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  javascriptCoBanSidebar: [{ type: 'autogenerated', dirName: 'javascript-co-ban' }],
  wordpressSidebar: [{ type: 'autogenerated', dirName: 'wordpress' }],
};

export default sidebars;